CREATE DATABASE TrierraSoft

USE TrierraSoft
GO

CREATE TABLE Parent (
	ParentID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ParentName VARCHAR(50) NOT NULL
)

CREATE TABLE Child (
	ChildID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ParentID INT NOT NULL,
	ChildName VARCHAR(50) NOT NULL,
	FOREIGN KEY (ParentID) REFERENCES Parent(ParentID)
)